import { describe, it, expect } from "vitest";
import { validateRoute } from "../src/dispatch/validate-route.js";
import { DEFAULT_MANIFESTS } from "../src/dispatch/run-dispatch.js";
import { DISPATCH_FIXTURES } from "./fixtures/dispatch-briefs.js";
import type { Sidecar } from "../src/sidecar/types.js";

/**
 * CROSS-VOCABULARY PROBE — every registered manifest against every FOREIGN
 * brief, frozen as a snapshot (offline, zero LLM, zero quota).
 *
 * What it measures that nothing else does. Two probes already exist and both
 * are blind to the same thing:
 *   - the fail-closed detector in `paramFilled` catches a FORGOTTEN `pattern`;
 *   - the generic discrimination probe (`dispatch-manifest-probe`) feeds prose
 *     carrying NO card vocabulary, which catches a LAZY pattern only when the
 *     laziness shows on vocabulary-free text.
 * Measured on 2026-07-29: widening WF-005's `Intelligence scope` to a bare `AI`
 * token left all 308 tests green, because the neutral brief carries no AI
 * vocabulary and every other case involving that spec expects it filled. That
 * is the hole this probe closes, across every manifest at once.
 *
 * IT IS NOT AN ASSERTION OF CORRECTNESS, and must not become one. A filled
 * foreign cell is not mechanically a defect: a brief stating GDPR HAS stated a
 * compliance stake, so WF-004's `Priority stakes` legitimately fills on a
 * WF-001 brief (already recorded in that manifest's own test). What is refused
 * is an UNNOTICED change — so the matrix is snapshotted, and the value is in
 * READING the diff when it moves, never in the red/green.
 *
 * When a new manifest lands the snapshot necessarily changes. Regenerate it
 * deliberately (`vitest -u`) and read the diff; a reflexive update turns this
 * file into a rubber stamp, which is worse than not having it.
 *
 * Run at five manifests rather than ten, on purpose: waiting for the tenth
 * would let five more manifests be written under a policy that may have
 * drifted.
 */

/** Minimal sidecar exposing every registered manifest as a resolvable route. */
const PROBE_SIDECAR: Sidecar = {
  schemaVersion: "1.0",
  catalog: { name: "claude-agents", version: "v4.2.0" },
  generatedAt: "2026-07-29T00:00:00Z",
  assets: Object.keys(DEFAULT_MANIFESTS).map((id) => ({
    id,
    type: "workflow" as const,
    path: `workflows/${id}.md`,
    title: id,
    description: "cross-vocabulary probe",
    catalogVersion: "v4.2.0",
    source: { file: `workflows/${id}.md`, catalogTag: "v4.2.0" },
  })),
};

/** Briefs that reach routing: P18 dies at intake and carries no brief. */
const ROUTABLE = DISPATCH_FIXTURES.filter((f) => f.brief !== undefined);

/**
 * Which required card labels this brief FILLS for this manifest — computed
 * through the real `validateRoute`, so the probe cannot drift from the code it
 * measures. Specs carrying `defaultValue` can never be missing and are excluded:
 * they say so, and counting them would inflate every row.
 */
function filledCards(manifestId: string, brief: (typeof ROUTABLE)[number]["brief"]): string[] {
  const manifest = DEFAULT_MANIFESTS[manifestId];
  if (manifest === undefined || brief === undefined) throw new Error(`no manifest ${manifestId}`);
  const measurable = manifest.params.filter((p) => p.required && p.defaultValue === undefined);
  const decision = validateRoute(
    { proposedRoute: manifestId, rationale: "cross-vocabulary probe", nearestMiss: null },
    { ...brief, constraints: [...brief.constraints] },
    PROBE_SIDECAR,
    DEFAULT_MANIFESTS,
  );
  const missing = decision.status === "PARAMS_MISSING" ? decision.missingParams : [];
  return measurable.map((p) => p.card).filter((card) => !missing.includes(card));
}

function renderMatrix(): string {
  const lines: string[] = [
    "# Cross-vocabulary matrix — snapshot, read the diff",
    "",
    "Generated by `test/dispatch-cross-vocabulary-probe.test.ts`. Each manifest is run",
    "against every FOREIGN coverage-matrix brief (a brief whose expected route is another",
    "workflow, including the four honest NO_MATCH briefs). A listed cell means the",
    "detector accepted prose written for a different card.",
    "",
    "**A filled cell is not automatically a defect** — some facts legitimately cross cards",
    "(GDPR is both a compliance stake and a technical constraint). It is a defect when the",
    "spec fills on vocabulary that says nothing about ITS OWN card. Read, decide, and record",
    "the decision on the spec — never silently regenerate.",
    "",
  ];

  for (const id of Object.keys(DEFAULT_MANIFESTS).sort()) {
    const manifest = DEFAULT_MANIFESTS[id];
    const measurable =
      manifest?.params.filter((p) => p.required && p.defaultValue === undefined).length ?? 0;
    const foreign = ROUTABLE.filter((f) => f.expected !== id);
    const rows = foreign
      .map((f) => ({ id: f.id, expected: f.expected, cards: filledCards(id, f.brief) }))
      .filter((r) => r.cards.length > 0);
    const cellCount = rows.reduce((n, r) => n + r.cards.length, 0);

    lines.push(
      `## ${id} — ${measurable} measurable specs × ${foreign.length} foreign briefs`,
      "",
      `Foreign fills: **${cellCount}** cell(s) over ${rows.length} brief(s).`,
      "",
    );
    if (rows.length === 0) {
      lines.push("_No foreign brief fills any spec of this manifest._", "");
      continue;
    }
    lines.push("| Foreign brief | Written for | Specs it fills |", "|---|---|---|");
    for (const r of rows) {
      lines.push(`| ${r.id} | ${r.expected} | ${[...r.cards].sort().join(" · ")} |`);
    }
    lines.push("");
  }
  return lines.join("\n");
}

describe("cross-vocabulary probe — a frozen matrix, not a verdict", () => {
  it("matches the reviewed snapshot of foreign fills", async () => {
    await expect(renderMatrix()).toMatchFileSnapshot(
      "./__snapshots__/cross-vocabulary-matrix.md",
    );
  });

  it("measures something: every manifest is exercised against foreign briefs", () => {
    // Guard the guard. If the fixture set or the registry were ever filtered
    // down, the snapshot could go empty and still pass as "no leak".
    expect(Object.keys(DEFAULT_MANIFESTS).length).toBeGreaterThanOrEqual(5);
    for (const id of Object.keys(DEFAULT_MANIFESTS)) {
      expect(ROUTABLE.filter((f) => f.expected !== id).length).toBeGreaterThan(10);
    }
  });
});
